Create Table Livro
(
   PK_liv 	Integer Not Null Primary key,
   Titulo 	Varchar (50), 
   Num_pag 	Smallint,
   Ano 		Smallint
); 

/*ALTERANDO O TIPO*/
ALTER TABLE Livro
MODIFY Ano varchar(10);

/*ALTERARNDO O NOME DA VAROAVEL*/
ALTER TABLE Livro
CHANGE Titulo Nome varchar(50);

/*ADICIONANDO NOVA VARIAVEL*/
ALTER TABLE Livro
ADD Teste INT NOT NULL;

/*DELETAR VARIAVEL*/
ALTER TABLE Livro
DROP COLUMN Teste;

/*EXERCICIO*/

/*EXCLUIR CAMPO*/
ALTER TABLE Livro
DROP COLUMN PK_liv; 

/*ACIDIONAR UMA CHAVE PRIMAN NA TABELA LIVRO*/
ALTER TABLE Livro
ADD Primary Key (teste);

/*INSERIR UM NOVO CAMPO DA TABELA LIBRO*/
ALTER TABLE Livro
ADD CPF CHAR(11) NOT NULL;

/*ALTERAR A TIPO DE DADO EM UM CAMPO*/
ALTER TABLE Livro
MODIFY CPF VARCHAR(10);

ALTER TABLE Livro
MODIFY CPF VARCHAR(10);

/*ALTERAR O NOME DE UM CAMPO*/
ALTER TABLE Livro
CHANGE CPF CNPJ varchar(50);


SELECT 
FROM trab
INNER JOIN emp
   ON 
INNER JOIN cia
   ON  