-- codigo de altomatização de sincronia de uma tabela que éa junção 3 tabelas
CREATE OR REPLACE FUNCTION DELETE_LOCACAO
RETURNS TRIGGER AS
$$
BEGIN

    DELETE FROM RELATORIO_LOCADORA
    WHERE IDLOCACAO = OLD.IDLOCACAO;
    
    COPY RELATORIO_LOCADORA TO
    'C:\CODE\PraticaBasica\SQL\Praticas_Podtgres_SQL\RELATORIO_LOCADORA.csv'
    DELIMITER ';'
    CSV HEADER;

RETURN OLD
END;
$$
LANGUAGE plpgsql;


CREATE TRIGGER DELETE_REG
    BEFORE DELETE ON LOCACAO 
    FOR EACH ROW
    EXECUTE PROCEDURE DELETE_LOCACAO;

SELECT * FROM LOCACAO;
SELECT* FROM RELATORIO_LOCADORA;

DELETE FROM LOCACAO 
whereq IDLOCACAO = 1;